# Generated by Django 3.0.7 on 2020-06-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HindiMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi_meaning', models.CharField(max_length=1000)),
                ('grammar', models.CharField(blank=True, max_length=100, null=True)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='do_translate.EnglishWord')),
            ],
        ),
    ]
